const RecipeApi = [
    {
        id:1,
        category:"Breakfast",
        name:"fried egg",
        price:100,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/egg.jpg",
    },
    {
        id:2,
        category:"Breakfast",
        name:"halwapuri",
        price:300,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/halwapuri.jpg",
    },
    {
        id:3,
        category:"Breakfast",
        name:"Channay",
        price:200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Channay.jpg",
    },
    {
        id:4,
        category:"Breakfast",
        name:"Paratha",
        price:70,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/paratha.jpg",
    },
    {
        id:5,
        category:"Breakfast",
        name:"ommelete",
        price:300,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/ommelete.jpg",
    },
    {
        id:6,
        category:"Main course",
        name:"Biryani",
        price:300,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Biryani.jpg",
    },
    {
        id:7,
        category:"Main course",
        name:"Chicken karahi full",
        price:2000,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Chicken karahi.jpg",
    },
    {
        id:8,
        category:"Main course",
        name:"mutton karahi",
        price:3000,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/mutton karahi.jpg",
    },
    {
        id:9,
        category:"Main course",
        name:"vegetable",
        price:500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/vegetable.jpg",
    },
    {
        id:10,
        category:"Main course",
        name:"Palak paneer",
        price:600,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Palak paneer.jpg",
    },
    {
        id:11,
        category:"Main course",
        name:"chilli dry with Fried rice",
        price:1200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/chilli dry with Fried rice.jpg",
    },
    {
        id:12,
        category:"Main course",
        name:"chicken chow man",
        price:800,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/chicken chow man.jpg",
    },
    {
        id:13,
        category:"Main course",
        name:"chicken stake",
        price:1200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"chicken stake.jpg",
    },
    {
        id:14,
        category:"Main course",
        name:"Beef stake",
        price:2200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Beef stake.jpg",
    },
    {
        id:15,
        category:"Main course",
        name:"beef pulao",
        price:1200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/beef pulao.jpg",
    },
    {
        id:16,
        category:"BBQ",
        name:"chikken tikka boti",
        price:1200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/chikken tikka boti.jpg",
    },
    {
        id:17,
        category:"BBQ",
        name:"chikken malai boti",
        price:1500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/chikken malai boti.jpg",
    },
    {
        id:18,
        category:"BBQ",
        name:"Chicken kabab",
        price:1500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Chicken kabab.jpg",
    },
    {
        id:19,
        category:"BBQ",
        name:"Reshmi kabab",
        price:1200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Reshmi kabab.jpg",
    },
    {
        id:20,
        category:"BBQ",
        name:"Fish tikka",
        price:2600,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Fish tikka.jpg",
    },
    {
        id:21,
        category:"BBQ",
        name:"BBQ platter",
        price:3500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/BBQ platter.jpg",
    },
    {
        id:22,
        category:"Beverages",
        name:"Mint margaretaa",
        price:500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Mint margaretaa.jpg",
    },
    {
        id:23,
        category:"Beverages",
        name:"Strawbary lemonade",
        price:500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Strawbary lemonade.jpg",
    },
    {
        id:24,
        category:"Beverages",
        name:"Pina colada",
        price:500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Pina colada.jpg",
    },
    {
        id:25,
        category:"Beverages",
        name:"Cold coffee",
        price:800,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Cold coffee.jpg",
    },
    {
        id:26,
        category:"Beverages",
        name:"Apple juice",
        price:500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Apple juice.jpg",
    },
    {
        id:27,
        category:"Beverages",
        name:"Capachino coffee",
        price:500,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Capachino coffee.jpg",
    },
    {
        id:28,
        category:"Beverages",
        name:"mango juice",
        price:300,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/mango juice.jpg",
    },
    {
        id:29,
        category:"Beverages",
        name:"Green tea",
        price:200,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/Green tea.jpg",
    },
    {
        id:30,
        category:"Beverages",
        name:"black coffee",
        price:300,
        description:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab, optio.",
        Image:"images/black coffee.jpg",
    },

]
export default RecipeApi;